name: nativeflow
description: "AI-powered real-time translation and voice assistant app with agentic capabilities."
publish_to: 'none' # This prevents accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animation (optimized)
  flutter_animate: ^4.5.2
  
  # Audio & Media
  flutter_soloud: ^3.1.10
  record: ^5.1.2
  flutter_tts: ^3.8.3
  
  # Networking & Real-time
  web_socket_channel: ^3.0.2
  
  # File & Storage
  path_provider: ^2.1.5
  
  # Utils & Logging
  logging: ^1.2.0
  logger: ^2.0.0
  
  # UI Icons
  cupertino_icons: ^1.0.2
  
  # Camera & Media
  camera: ^0.11.1
  camera_web: ^0.3.5
  
  # Firebase Backend
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.6
  
  # App Store Preparation
  package_info_plus: ^8.0.2
  permission_handler: ^11.0.1
  
  # Professional UI Components
  shimmer: ^3.0.0
  lottie: ^3.1.2
  
  # State Management & Architecture
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Networking & HTTP
  http: ^1.2.2
  dio: ^5.7.0
  
  # Device Features
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.0.5
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # App Store Assets Generation
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  
  # Code Generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"

# Splash Screen Configuration
flutter_native_splash:
  color: "#4D96FF"
  image: "assets/splash/splash_logo.png"
  branding: "assets/splash/branding.png"
  android_12:
    image: "assets/splash/splash_logo_android12.png"
    color: "#4D96FF"
    icon_background_color: "#ffffff"
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/splash/
    - assets/images/
    - assets/lottie/
    - web/pcm-processor.js

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700