name: google_flow
description: "A new Flutter project for Google Flow integration."
publish_to: 'none' # This prevents accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_soloud: ^3.1.10
  record: ^5.1.2
  web_socket_channel: ^3.0.2
  path_provider: ^2.1.5
  logging: ^1.2.0
  cupertino_icons: ^1.0.2
  # Camera support
  camera: ^0.11.1
  camera_web: ^0.3.5
  # Firebase dependencies
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.6
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and update the following if we have assets we wanna include
  # assets:
  #   - web/pcm-processor.js


  # Uncomment and update the following if you use custom fonts later on to make it look purrty 
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700